version: '3.8'

services:
  aircnc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aircnc
    depends_on:
      - mongo
    env_file: .env
    ports:
      - 4000:4000
    command: npm run dev
    volumes:
      - app-data:/app
      - ./src:/app/src
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - ${DB_PORT}:${PORT}
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER_NAME}:${DB_PASSWORD}@mongo:${DB_PORT}

volumes:
  app-data:
    driver: local
  db-data:
